name: "file_center"

services:
  api:
    build: .

    ports:
      - "4000:4000"
    
    environment:
      - DB_HOST=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    secrets:
      - source: mater_key
        target: /rails/config/master.key

    depends_on:
      - postgres

  postgres:
    image: postgres:16.1
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD

volumes:
  postgres-data:

secrets:
  mater_key:
    file: ./config/master.key
