name: "file_center"

services:
  api:
    build: .

    ports:
      - "4000:4000"
    
    environment:
      - DB_HOST=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}

    depends_on:
      - postgres

  postgres:
    image: postgres:16.1
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD

volumes:
  postgres-data:
